manifest:
  version: 1.2
  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr.git
      revision: v4.1.0
      path: zephyr
      import:
        name-allowlist:
          - hal_stm32
          - cmsis
      west-commands: scripts/west-commands.yml
    - name: libcsp
      url: https://github.com/libcsp/libcsp.git
      revision: v2.0
      path: modules/lib/libcsp
